# Generated by Django 5.0.6 on 2024-06-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_doorlog_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoorLog',
        ),
    ]
