version: "3.3"

services:
  office:
    build: ./office
    container_name: office
    restart: unless-stopped
    environment:
      DB_URI: postgresql+psycopg2://dbuser:dbpass@db/office
      SECRET_KEY: "changeme"
      ALLOWED_HOSTS: "127.0.0.1"
      CSRF_TRUSTED_ORIGINS: "https://changeme"
      CORS_ALLOWED_ORIGINS: "https://changeme"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "127.0.0.1:5000:5000"
    links:
      - db

  db:
    image: 'docker.io/library/postgres:latest'
    restart: unless-stopped
    environment:
      POSTGRES_USER: dbuser
      PG_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: office
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      timeout: 5s
      interval: 10s
      retries: 10
